### ISSUE TITLE
Parallel Program Request

### ISSUE THREAD

**Issue by jbccollins** [solelychloe/parallel.report#1]
I have the Parallel Program emblem and I would like to get added to the Parallel Program Report site.

- [x] I understand that this website is not affiliated with Bungie, Inc. in any way.

Bungie Name: My Derpy Turtle#6665

My contribution: Small css changes to Guardian Theater way back in the day

**Comment by SapphoSys** [comment]
Added as per [4bef485](https://github.com/solelychloe/parallel.report/commit/4bef48504d198a84b8f06aba534d214fb75b3b3f). Let me know if you wanna change your name, role, or the link provided in the site.

**Comment by jbccollins** [comment]
Looks good to me :) Thanks!
